### ISSUE TITLE
Exercise options location - alternative to configuring before exercise screen

### ISSUE THREAD

**Issue by b-cheek** [b-cheek/ChordCaptain#1]
Regarding:

> this page should be more or less consolidated with generic options to start that user adjusts

What do you think of sending users straight to the new exercise (with the sheet music) with these generic options, and allowing them to configure with the "Edit Parameters" button as they see fit? I think throwing all the options at the user right away could be overwhelming, and it would be good to get them to the generate button as quick as possible to showcase the product.

Specification reference:
![New exercise specification image](https://github.com/b-cheek/ChordCaptain/blob/master/docs/specification_images/page1.JPG?raw=true "New exercise specification image")

**Comment by Modponens** [comment]
I like this idea better than the original thought. It's important that the users don't have too hard of a time getting to any exercise. Maybe we could make those generic parameters reflect something universally appreciated like a Bb diatonic exercise.
