### ISSUE TITLE
Key signature selection mode - alternative to dropdown

### ISSUE THREAD

**Issue by b-cheek** [b-cheek/ChordCaptain#3]
Regarding:

> Key signature drop down

I think key signature might be cumbersome as a drop down because of the amount of options, especially using the staff indicator showing flats/sharps. What do you think is a good alternative? I think just typing in the key signature (e.g. "Ab," "F#") and then having maybe a major/minor radio button option is easiest, and we could also possibly incorporate the number of sharps/flats or the image of the key signature on the staff alongside this when the key signature is selected.

Specification reference:
![New exercise specification image](https://github.com/b-cheek/ChordCaptain/blob/master/docs/specification_images/page1.JPG?raw=true "New exercise specification image")

**Comment by Modponens** [comment]
I think you're idea is fine- no need to display more than one key signature at a time
