### ISSUE TITLE
"Instrument" range selection mode side effects

### ISSUE THREAD

**Issue by b-cheek** [b-cheek/ChordCaptain#6]
If the users opts to use the "instrument" range selection mode, should that automatically update any clef, transposition, or playback information, or is it just for range?

Specification reference:
![New exercise specification image](https://github.com/b-cheek/ChordCaptain/blob/master/docs/specification_images/page1.JPG?raw=true "New exercise specification image")

**Comment by Modponens** [comment]
I think it should be just used for the final output of range after transposition.
