### ISSUE TITLE
Bottom/Top note range selection mode - alternative to drop down

### ISSUE THREAD

**Issue by b-cheek** [b-cheek/ChordCaptain#8]
I'm not sure if you were implying a drop down with this, but I think the best end solution would be a smart way to select the top and bottom notes on one staff. I think this would be outside the scope of v1.0 though, and maybe we could just type in note names for now (e.g. "A2" or "C4").

Specification reference:
![New exercise specification image](https://github.com/b-cheek/ChordCaptain/blob/master/docs/specification_images/page1.JPG?raw=true "New exercise specification image")

**Comment by Modponens** [comment]
This seems just fine, but I like your idea about selecting the note on a staff for later versions
